from __future__ import annotations

from idempotency_http_fixtures import AGENT_HEADERS, WORKSPACE_HEADERS
from idempotency_http_terminal_case import RouteCase
from idempotency_http_terminal_decision_cases import DECISION_ROUTE_CASES

BASE_ROUTE_CASES = (
    RouteCase(
        "grant-success",
        "grant.issue.v1",
        "/v1/grants",
        {
            "agent_id": "agent_release",
            "scopes": ["write:repo/feature/readme"],
            "ttl_seconds": 60,
        },
        WORKSPACE_HEADERS,
        201,
        "grants",
        1,
        1,
    ),
    RouteCase(
        "grant-service-400",
        "grant.issue.v1",
        "/v1/grants",
        {"agent_id": "agent_release", "scopes": ["bad scope"], "ttl_seconds": 60},
        WORKSPACE_HEADERS,
        400,
        "grants",
        0,
        0,
    ),
    RouteCase(
        "grant-bounds-missing-403",
        "grant.issue.v1",
        "/v1/grants",
        {
            "agent_id": "agent_unbounded",
            "scopes": ["write:repo/feature/readme"],
            "ttl_seconds": 60,
        },
        WORKSPACE_HEADERS,
        403,
        "grants",
        0,
        1,
    ),
    RouteCase(
        "grant-scope-bounds-403",
        "grant.issue.v1",
        "/v1/grants",
        {"agent_id": "agent_release", "scopes": ["read:secret/env"], "ttl_seconds": 60},
        WORKSPACE_HEADERS,
        403,
        "grants",
        0,
        1,
    ),
    RouteCase(
        "grant-ttl-bounds-403",
        "grant.issue.v1",
        "/v1/grants",
        {
            "agent_id": "agent_release",
            "scopes": ["write:repo/feature/readme"],
            "ttl_seconds": 3_601,
        },
        WORKSPACE_HEADERS,
        403,
        "grants",
        0,
        1,
    ),
    RouteCase(
        "token-success",
        "subject_token.mint.v1",
        "/v1/tokens",
        {"grant_ref": "grt_seed", "audience": "pep_main", "ttl_seconds": 60},
        AGENT_HEADERS,
        201,
        "tokens",
        1,
        1,
    ),
    RouteCase(
        "token-forbidden",
        "subject_token.mint.v1",
        "/v1/tokens",
        {"grant_ref": "grt_missing", "audience": "pep_main", "ttl_seconds": 60},
        AGENT_HEADERS,
        403,
        "tokens",
        0,
        1,
    ),
    RouteCase(
        "boundary-success",
        "boundary.create.v1",
        "/v1/boundaries",
        {
            "name": "matrix-boundary",
            "runtime": "codex",
            "boundary_type": "pretooluse",
            "mode": "fail_closed",
        },
        WORKSPACE_HEADERS,
        201,
        "boundaries",
        1,
        1,
    ),
    RouteCase(
        "boundary-semantic-400",
        "boundary.create.v1",
        "/v1/boundaries",
        {
            "name": "matrix-boundary-invalid",
            "runtime": "unsupported",
            "boundary_type": "pretooluse",
            "mode": "fail_closed",
        },
        WORKSPACE_HEADERS,
        400,
        "boundaries",
        0,
        0,
    ),
    RouteCase(
        "rule-success",
        "auto_approval_rule.create.v1",
        "/v1/auto-approval-rules",
        {
            "name": "matrix-rule-route",
            "target_agent_id": "agent_release",
            "allowed_scopes": ["write:repo/feature/*"],
            "max_ttl_seconds": 3_600,
        },
        WORKSPACE_HEADERS,
        201,
        "rules",
        1,
        1,
    ),
    RouteCase(
        "rule-semantic-400",
        "auto_approval_rule.create.v1",
        "/v1/auto-approval-rules",
        {
            "name": "matrix-rule-invalid",
            "target_agent_id": "agent_release",
            "allowed_scopes": ["bad scope"],
            "max_ttl_seconds": 3_600,
        },
        WORKSPACE_HEADERS,
        400,
        "rules",
        0,
        0,
    ),
    RouteCase(
        "approve-success",
        "grant_request.approve.v1",
        "/v1/grant-requests/grq_approve/approve",
        {},
        WORKSPACE_HEADERS,
        200,
        "requests",
        1,
        2,
    ),
    RouteCase(
        "approve-not-found",
        "grant_request.approve.v1",
        "/v1/grant-requests/grq_missing/approve",
        {},
        WORKSPACE_HEADERS,
        404,
        "requests",
        0,
        0,
    ),
    RouteCase(
        "approve-not-pending",
        "grant_request.approve.v1",
        "/v1/grant-requests/grq_approve_done/approve",
        {},
        WORKSPACE_HEADERS,
        409,
        "requests",
        0,
        0,
    ),
    RouteCase(
        "approve-nested-400",
        "grant_request.approve.v1",
        "/v1/grant-requests/grq_approve_bad/approve",
        {},
        WORKSPACE_HEADERS,
        400,
        "requests",
        0,
        0,
    ),
    RouteCase(
        "approve-nested-403",
        "grant_request.approve.v1",
        "/v1/grant-requests/grq_approve_bounds/approve",
        {},
        WORKSPACE_HEADERS,
        403,
        "requests",
        0,
        1,
    ),
)

ROUTE_CASES = BASE_ROUTE_CASES + DECISION_ROUTE_CASES
