from idempotency_http_terminal_models import (
    _NESTED_GRANT_KEYS,
    _REQUEST_KEYS,
    _REQUEST_STATIC,
    ExpectedTerminalResponse,
    _error,
)

GRANT_REQUEST_RESPONSES = {
    "approve-success": ExpectedTerminalResponse(
        200,
        exact_values=(
            *_REQUEST_STATIC,
            (("decided_at",), "2026-07-19T12:00:00+00:00"),
            (("decided_by",), "workspace:ws_main"),
            (("request_id",), "grq_approve"),
            (("status",), "approved"),
            (("target_agent_id",), "agent_release"),
            (("grant", "agent_id"), "agent_release"),
            (("grant", "expires_at"), "2026-07-19T13:00:00+00:00"),
            (("grant", "scopes"), ["write:repo/feature/readme"]),
        ),
        prefixed_values=(
            (("audit_event_id",), "evt_"),
            (("issued_grant_ref",), "grt_"),
            (("grant", "grant_id"), "grnt_"),
            (("grant", "grant_ref"), "grt_"),
        ),
        object_keys=(
            ((), _REQUEST_KEYS | {"audit_event_id", "grant"}),
            (("grant",), _NESTED_GRANT_KEYS),
        ),
    ),
    "approve-not-found": _error(404, "grant_request_not_found", "grant_request_not_found"),
    "approve-not-pending": _error(409, "grant_request_not_pending", "grant_request_not_pending"),
    "approve-nested-400": _error(
        400,
        "invalid_requested_scope",
        "invalid_requested_scope",
    ),
    "approve-nested-403": _error(403, "issuable_bounds_not_found", "issuable_bounds_not_found"),
    "reject-success": ExpectedTerminalResponse(
        200,
        exact_values=(
            *_REQUEST_STATIC,
            (("decided_at",), "2026-07-19T12:00:00+00:00"),
            (("decided_by",), "workspace:ws_main"),
            (("issued_grant_ref",), None),
            (("request_id",), "grq_reject"),
            (("status",), "rejected"),
            (("target_agent_id",), "agent_release"),
        ),
        prefixed_values=((("audit_event_id",), "evt_"),),
        object_keys=(((), _REQUEST_KEYS | {"audit_event_id"}),),
    ),
    "reject-not-found": _error(404, "grant_request_not_found", "grant_request_not_found"),
    "reject-not-pending": _error(409, "grant_request_not_pending", "grant_request_not_pending"),
    "auto-success": ExpectedTerminalResponse(
        200,
        exact_values=(
            *_REQUEST_STATIC,
            (("decided_at",), "2026-07-19T12:00:00+00:00"),
            (("decided_by",), "workspace:ws_main"),
            (("decision_reason",), "auto_approval_rule:aar_seed_1"),
            (("request_id",), "grq_auto"),
            (("status",), "approved"),
            (("target_agent_id",), "agent_release"),
            (("auto_approval", "decision"), "approved"),
            (("auto_approval", "reason"), "grant_request_auto_approved"),
            (("auto_approval", "rule_id"), "aar_seed_1"),
            (("grant", "agent_id"), "agent_release"),
        ),
        prefixed_values=(
            (("audit_event_id",), "evt_"),
            (("issued_grant_ref",), "grt_"),
            (("grant", "grant_id"), "grnt_"),
            (("grant", "grant_ref"), "grt_"),
        ),
        object_keys=(
            ((), _REQUEST_KEYS | {"audit_event_id", "auto_approval", "grant"}),
            (
                ("auto_approval",),
                frozenset({"decision", "reason", "rule_id"}),
            ),
            (("grant",), _NESTED_GRANT_KEYS),
        ),
    ),
    "auto-would-not-approve": ExpectedTerminalResponse(
        200,
        exact_values=(
            *_REQUEST_STATIC,
            (("decided_at",), None),
            (("decided_by",), None),
            (("request_id",), "grq_auto_unmatched"),
            (("routing_hint",), "manual_review_required"),
            (("routing_reason",), "no_matching_rule"),
            (("status",), "pending"),
            (("target_agent_id",), "agent_unmatched"),
            (("auto_approval", "decision"), "would_not_approve"),
            (("auto_approval", "reason"), "no_matching_rule"),
        ),
        object_keys=(
            ((), _REQUEST_KEYS | {"auto_approval", "routing_hint", "routing_reason"}),
            (("auto_approval",), frozenset({"decision", "reason"})),
        ),
    ),
    "auto-not-found": _error(404, "grant_request_not_found", "grant_request_not_found"),
    "auto-not-pending": _error(409, "grant_request_not_pending", "grant_request_not_pending"),
    "auto-nested-400": _error(
        400,
        "invalid_issuable_scope_bound",
        "invalid_issuable_scope_bound",
    ),
    "auto-nested-403": _error(403, "issuable_bounds_not_found", "issuable_bounds_not_found"),
}
