"""Vinctor service-layer application helpers."""

from vinctor_service.audit import AuditWriter, InMemoryAuditWriter
from vinctor_service.authorize import authorize_action
from vinctor_service.auto_approval import (
    auto_approve_grant_request,
    create_auto_approval_rule,
    disable_auto_approval_rule,
    evaluate_auto_approval,
    list_auto_approval_rules,
    upsert_auto_approval_rule,
)
from vinctor_service.auto_approval_http import handle_v1_auto_approval_rules_http
from vinctor_service.boundary_http import WorkspaceIdentity, handle_v1_boundaries_http
from vinctor_service.grant_http import handle_v1_grants_http
from vinctor_service.grant_request_http import handle_v1_grant_requests_http
from vinctor_service.grant_requests import (
    approve_grant_request,
    create_grant_request,
    list_grant_requests,
    lookup_grant_request,
    reject_grant_request,
)
from vinctor_service.grants import (
    AgentIssuableScopeBoundsRepository,
    InMemoryAgentIssuableScopeBoundsRepository,
    issue_grant,
    lookup_grant,
    revoke_grant,
    validate_issuable_scope_bounds,
)
from vinctor_service.in_memory import InMemoryV1Service
from vinctor_service.keys import (
    AGENT_KEY_PREFIX,
    AUDITOR_KEY_PREFIX,
    PEP_KEY_PREFIX,
    SERVICE_OPERATOR_KEY_PREFIX,
    WORKSPACE_KEY_PREFIX,
    CreatedLocalKey,
    LocalKeyRecord,
    SQLiteLocalKeyRepository,
    mask_key,
)
from vinctor_service.local_http import create_v1_http_handler, create_v1_http_server
from vinctor_service.metrics import Metrics
from vinctor_service.models import (
    AuthorizationRequest,
    AuthorizationResponse,
    AutoApprovalEvaluationResult,
    AutoApprovalRule,
    GrantIssueRequest,
    GrantIssueResult,
    GrantRequest,
    GrantRequestCreateRequest,
    GrantRequestCreateResult,
    GrantRequestDecisionResult,
    GrantRequestRoutingHint,
    SubjectToken,
    V1DelegatedEnforceRequest,
    V1EnforceRequest,
    V1EnforceResponse,
    V1ObserveRequest,
    V1ObserveResponse,
    V1SimulateRequest,
    V1SimulateResponse,
)
from vinctor_service.postgres import (
    PostgresAuditWriter,
    PostgresGrantRepository,
    PostgresV1Service,
    connect_postgres,
    init_postgres_schema,
)
from vinctor_service.repositories import (
    AgentEnforcementSettingsRepository,
    AutoApprovalRuleRepository,
    GrantLifecycleRepository,
    GrantRepository,
    GrantRequestRepository,
    InMemoryAgentEnforcementSettingsRepository,
    InMemoryAutoApprovalRuleRepository,
    InMemoryGrantRepository,
    InMemoryGrantRequestRepository,
    InMemorySubjectTokenRepository,
    SubjectTokenRepository,
)
from vinctor_service.service_config import ServiceRuntimeConfig, load_service_runtime_config
from vinctor_service.service_runtime import (
    ServiceRuntimeHandle,
    prepare_service_runtime,
    render_service_runtime_banner,
)
from vinctor_service.simulations import simulate_v1_contract
from vinctor_service.sqlite import (
    SQLiteAgentEnforcementSettingsRepository,
    SQLiteAgentIssuableScopeBoundsRepository,
    SQLiteAuditWriter,
    SQLiteAutoApprovalRuleRepository,
    SQLiteBoundaryRegistry,
    SQLiteGrantRepository,
    SQLiteGrantRequestRepository,
    SQLiteSubjectTokenRepository,
    SQLiteV1Service,
    get_sqlite_schema_versions,
    init_sqlite_schema,
    insert_grant,
)
from vinctor_service.storage_runtime import DecisionStorageHandle, prepare_decision_storage
from vinctor_service.subject_tokens import SubjectTokenMintResult
from vinctor_service.v1_enforce import delegated_enforce_v1_contract, enforce_v1_contract
from vinctor_service.v1_http import (
    AgentIdentity,
    PepIdentity,
    V1HttpResponse,
    V1ObserveService,
    V1SimulateService,
    V1TokenService,
    handle_v1_delegated_enforce_http,
    handle_v1_enforce_http,
    handle_v1_observe_http,
    handle_v1_simulate_http,
    handle_v1_tokens_http,
)

__all__ = [
    "AgentIdentity",
    "AUDITOR_KEY_PREFIX",
    "AuthorizationRequest",
    "AuthorizationResponse",
    "AutoApprovalEvaluationResult",
    "AutoApprovalRule",
    "AutoApprovalRuleRepository",
    "AuditWriter",
    "AGENT_KEY_PREFIX",
    "CreatedLocalKey",
    "DecisionStorageHandle",
    "AgentEnforcementSettingsRepository",
    "AgentIssuableScopeBoundsRepository",
    "GrantIssueRequest",
    "GrantIssueResult",
    "GrantLifecycleRepository",
    "GrantRequest",
    "GrantRequestCreateRequest",
    "GrantRequestCreateResult",
    "GrantRequestDecisionResult",
    "GrantRequestRoutingHint",
    "GrantRequestRepository",
    "GrantRepository",
    "InMemoryAgentEnforcementSettingsRepository",
    "InMemoryAgentIssuableScopeBoundsRepository",
    "InMemoryAutoApprovalRuleRepository",
    "InMemoryAuditWriter",
    "InMemoryGrantRepository",
    "InMemoryGrantRequestRepository",
    "InMemorySubjectTokenRepository",
    "InMemoryV1Service",
    "LocalKeyRecord",
    "Metrics",
    "PEP_KEY_PREFIX",
    "PepIdentity",
    "PostgresAuditWriter",
    "PostgresGrantRepository",
    "PostgresV1Service",
    "SQLiteAgentEnforcementSettingsRepository",
    "SQLiteAgentIssuableScopeBoundsRepository",
    "SQLiteAuditWriter",
    "SQLiteAutoApprovalRuleRepository",
    "SQLiteBoundaryRegistry",
    "SQLiteGrantRepository",
    "SQLiteGrantRequestRepository",
    "SQLiteLocalKeyRepository",
    "SERVICE_OPERATOR_KEY_PREFIX",
    "SQLiteSubjectTokenRepository",
    "SQLiteV1Service",
    "ServiceRuntimeConfig",
    "ServiceRuntimeHandle",
    "SubjectToken",
    "SubjectTokenMintResult",
    "SubjectTokenRepository",
    "V1DelegatedEnforceRequest",
    "V1EnforceRequest",
    "V1EnforceResponse",
    "V1HttpResponse",
    "V1ObserveRequest",
    "V1ObserveResponse",
    "V1ObserveService",
    "V1SimulateRequest",
    "V1SimulateResponse",
    "V1SimulateService",
    "V1TokenService",
    "WORKSPACE_KEY_PREFIX",
    "WorkspaceIdentity",
    "approve_grant_request",
    "auto_approve_grant_request",
    "authorize_action",
    "create_auto_approval_rule",
    "create_grant_request",
    "create_v1_http_handler",
    "create_v1_http_server",
    "connect_postgres",
    "delegated_enforce_v1_contract",
    "enforce_v1_contract",
    "evaluate_auto_approval",
    "get_sqlite_schema_versions",
    "handle_v1_boundaries_http",
    "handle_v1_auto_approval_rules_http",
    "handle_v1_delegated_enforce_http",
    "handle_v1_enforce_http",
    "handle_v1_observe_http",
    "handle_v1_simulate_http",
    "handle_v1_grant_requests_http",
    "handle_v1_grants_http",
    "handle_v1_tokens_http",
    "init_sqlite_schema",
    "init_postgres_schema",
    "insert_grant",
    "issue_grant",
    "list_auto_approval_rules",
    "list_grant_requests",
    "load_service_runtime_config",
    "lookup_grant_request",
    "lookup_grant",
    "mask_key",
    "prepare_service_runtime",
    "prepare_decision_storage",
    "reject_grant_request",
    "render_service_runtime_banner",
    "simulate_v1_contract",
    "revoke_grant",
    "disable_auto_approval_rule",
    "upsert_auto_approval_rule",
    "validate_issuable_scope_bounds",
]
